 cat > /etc/filebeat/filebeat.yml
 filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*
  exclude_lines: ['ELB-HealthChecker']
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
output.elasticsearch:
  hosts: ["10.1.2.100:9200","10.1.2.101:9200","10.1.2.102:9200"]
  username: "ESUSER"
  password: "ESPASS"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
monitoring.enabled: true
monitoring.cluster_uuid: "mt0otTWNSR2TjgwO2znzSA"
monitoring.elasticsearch:
  hosts: ["10.1.2.100:9200","10.1.2.101:9200","10.1.2.102:9200"]
  username: "ESUSER"
  password: "ESPASS"
